zones:
  - name: "salon"
    x1: -6.7
    y1: -2.6
    x2: 2.75
    y2: -0.44
    
  - name: "cocina"
    x1: -6.75
    y1: -0.41
    x2: -3.36
    y2: 2.42
    
  - name: "habitacion"
    x1: -3.25
    y1: -0.45
    x2: 2.66
    y2: 2.44
