zones:
  - name: "P1_1"
    x1: -2.5
    y1: -2.5
    x2: -1.8
    y2: 2.5

  - name: "P1_2"
    x1: -2.5
    y1: -2.5
    x2: 7.5
    y2: -1.9

  - name: "P1_3"
    x1: 6.9
    y1: -2.5
    x2: 7.5
    y2: 2.5

  - name: "P1_4"
    x1: -2.5
    y1: 1.9
    x2: 7.5
    y2: 2.5

  - name: "S1"
    x1: 5.5
    y1: -1.8
    x2: 6.75
    y2: -0.55

  - name: "P2"
    x1: 5.6
    y1: 0.55
    x2: 6.75
    y2: -0.55

  - name: "S2"
    x1: 5.55
    y1: 0.35
    x2: 6.8
    y2: 1.8

  - name: "S3"
    x1: 2.55
    y1: 0.35
    x2: 5.5
    y2: 1.85

  - name: "S4"
    x1: 1.4
    y1: 0.35
    x2: 2.55
    y2: 1.85

  - name: "P3"
    x1: 1.35
    y1: -0.7
    x2: 5.5
    y2: 0.25

  - name: "S5"
    x1: 1.35
    y1: -1.75
    x2: 5.5
    y2: -0.8

  - name: "S6"
    x1: -1.75
    y1: 0.4
    x2: 0.3
    y2: 1.8

  - name: "S7"
    x1: -1.75
    y1: -1.8
    x2: 0.4
    y2: -0.65

  - name: "P5"
    x1: -1.75
    y1: -0.65
    x2: 0.45
    y2: 0.45

  - name: "P6"
    x1: 0.45
    y1: -1.75
    x2: 1.3
    y2: -0.65

  - name: "P4"
    x1: 0.45
    y1: 0.5
    x2: 1.3
    y2: 1.85

  - name: "P7"
    x1: 0.4
    y1: -0.65
    x2: 1.4
    y2: 0.35