slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames (alineados con lo que ya publicas)
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    mode: mapping
    resolution: 0.05
    max_laser_range: 5.0
    minimum_time_interval: 0.0
    transform_publish_period: 0.02
